method: random
metric:
  name: test_acc
  goal: maximize
parameters:
  dataset_name:
    value: mnist
  epochs:
    value: 10
  optimizer:
    values: ['adam', 'sgd', 'adamW']
  fc_layer_size:
    values: [128, 256, 512, 1024]
  dropout:
    values: [0.0, 0.3, 0.5, 0.7]
  learning_rate:
    values: [0.00001, 0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03]
  batch_size:
    values: [1, 4, 8, 16, 32, 64, 128, 256]
  weight_decay:
    values: [0.0, 0.00001, 0.0001, 0.001, 0.01]