method: grid
metric:
  name: test_acc
  goal: maximize
parameters:
  dataset_name:
    value: mnist
  epochs:
    value: 10
  optimizer:
    values: ['adam', 'sgd', 'adamW']
  fc_layer_size:
    values: [128, 256, 512]
  dropout:
    values: [0.1, 0.2, 0.3]
  learning_rate:
    values: [0.001, 0.01, 0.1]
  batch_size:
    values: [4, 8, 16, 32, 64, 128, 256]
  weight_decay:
    values: [0.0, 0.001, 0.01]
  